{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lh-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lh-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lh-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "lh-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
