{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lh-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lh-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "configmaps", "serviceaccounts", "persistentvolumeclaims", "services"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["tlsroutes"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["littlehorse.io"]
  resources: ["*"]
  verbs: ["*"]
{{- if .Values.strimzi.enabled }}
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkausers", "kafkatopics", "kafkas", "kafkanodepools", "kafkarebalances"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
{{- end -}}
{{- if .Values.certManager.enabled }}
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
{{- end -}}
{{- if .Values.prometheus.enabled }}
- apiGroups: ["monitoring.coreos.com"]
  resources: ["podmonitors"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
{{- end -}}
{{- end }}
