{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lh-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lh-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "configmaps", "serviceaccounts", "persistentvolumeclaims", "services"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["littlehorse.io"]
  resources: ["*"]
  verbs: ["*"]
{{- if .Values.strimzi.enabled }}
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkausers", "kafkatopics"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
{{- end -}}
{{- if .Values.istio.enabled }}
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "gateways"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
{{- end -}}
{{- end }}
